// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransportManager.Data;

#nullable disable

namespace TransportManager.Migrations;

[DbContext(typeof(TransportDbContext))]
[Migration("20240808172736_AddDriversTable")]
partial class AddDriversTable {
  /// <inheritdoc />
  protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
    modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

    modelBuilder.Entity("TransportManager.Models.Driver", b => {
      b.Property<string>("Id").HasMaxLength(36).HasColumnType("TEXT");

      b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");

      b.Property<DateTime>("LicenseExpirationDate").HasColumnType("TEXT");

      b.Property<string>("LicenseNumber")
          .IsRequired()
          .HasMaxLength(20)
          .HasColumnType("TEXT");

      b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType(
          "TEXT");

      b.Property<string>("Status").IsRequired().HasColumnType("TEXT");

      b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");

      b.HasKey("Id");

      b.ToTable("Drivers", (string)null);
    });

    modelBuilder.Entity("TransportManager.Models.Vehicle", b => {
      b.Property<string>("Id").HasMaxLength(36).HasColumnType("TEXT");

      b.Property<double>("Capacity").HasColumnType("REAL");

      b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");

      b.Property<string>("LicensePlate")
          .IsRequired()
          .HasMaxLength(20)
          .HasColumnType("TEXT");

      b.Property<string>("Model").IsRequired().HasMaxLength(100).HasColumnType(
          "TEXT");

      b.Property<string>("Name").HasColumnType("TEXT");

      b.Property<int>("Status").HasColumnType("INTEGER");

      b.Property<int>("Type").HasColumnType("INTEGER");

      b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");

      b.Property<int>("Year").HasColumnType("INTEGER");

      b.HasKey("Id");

      b.ToTable("Vehicles", (string)null);
    });
#pragma warning restore 612, 618
  }
}
