global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using TransportManager.Data;
global using TransportManager.Models;
global using TransportManager.Repository;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using TransportManager.ViewModel;
global using TransportManager.Commands;
global using System.Runtime.CompilerServices;
global using System.Diagnostics;
global using Microsoft.EntityFrameworkCore;
global using BindableAttribute = Microsoft.UI.Xaml.Data.BindableAttribute;
global using Microsoft.EntityFrameworkCore.Design;
global using  System.ComponentModel.DataAnnotations;