using System.Collections.ObjectModel;

namespace TransportManager.Models;

public class CitiesManager {
  public static ObservableCollection<string> Cities { get; } = [
    "São Paulo",
    "Rio de Janeiro",
    "Belo Horizonte",
    "Salvador",
    "Brasília",
    "Curitiba",
    "Fortaleza",
    "Recife",
    "Porto Alegre",
    "Manaus",
    "Goiânia",
    "Belém",
    "Campinas",
    "São Luís",
    "Maceió",
    "Natal",
    "Teresina",
    "João Pessoa",
    "Aracaju",
    "Campo Grande",
    "Cuiabá",
    "Florianópolis",
    "Vitória",
    "Sorocaba",
    "Niterói",
    "Joinville",
    "Londrina",
    "Santos",
    "Uberlândia",
    "Ribeirão Preto",
    "São José dos Campos",
    "Feira de Santana",
    "Juiz de Fora",
    "Blumenau",
    "Caxias do Sul",
    "Maringá",
    "Piracicaba",
    "Bauru",
    "Montes Claros",
    "Rio Branco",
    "Barueri",
    "Caruaru",
    "Vila Velha",
    "Petrolina",
    "Cascavel",
    "São Carlos",
    "Taubaté",
    "Franca",
    "Macapá",
    "Foz do Iguaçu",
    "Buenos Aires",
    "Santiago",
    "Lima",
    "Bogotá",
    "Quito",
    "Montevideo",
    "Asunción",
    "La Paz",
    "Caracas",
    "Guadalajara",
    "Medellín",
    "Córdoba",
    "Mar del Plata",
    "Rosario",
    "Valparaíso"
  ];
}